added discriminator for learner and facilitator
uwblueprint/extend-a-family pull request #46
Opened 2024-06-28 02:08 UTC by cherryyng

## Notion ticket link
[Facilitator & Learner Relationship](https://www.notion.so/uwblueprintexecs/Facilitator-Learner-Relationship-20a31631fae246169c51ecb36c44b35c)

## Implementation description
* Added to base user model for learner and facilitator discriminators
* Added learner property to facilitators (list of strings)
* Added Facilitator property to learners (singular string)
* Created test in server.ts for saving to these user types

## Steps to test
1. Set up the .env with MG_DATABASE_NAME set to <name>_dev.
2. Run the server and verify that you can create and save documents with the new user types.
3. Check that the learners property for facilitators defaults to an empty array if not provided.
4. Ensure the facilitator property for learners is required and correctly assigned.

## What should reviewers focus on?
* Ensure the discriminators for the User model are correctly implemented.
* Verify the default value for the learners property.
* Confirm the facilitator property is required for learners and functions as expected.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

2024-07-12 01:00 UTC, jasondsouza35 requested changes
I think it looks good overall cherry! I just have one comment which is in a highlighted code block.

2024-07-12 05:47 UTC, achandrabalan approved these changes
LGTM 🔥

2024-07-12 06:37 UTC, carolynzhang18 reviewed
Lookin really good!!! Just a few small fixes in `user.mgmodel.ts`, verify those changes, and then you can go ahead and remove the testing stuff in `server.ts` as well :D

2024-07-12 06:37 UTC, carolynzhang18 commented on backend/models/user.mgmodel.ts
> +  collection: "user",
I think we can remove this `collection` option.

My understanding is that `collection` specifies the name of the collection for the model? You'll notice we already had a collection `users` and that specifying this option spawns another collection `user`. No need for both, just `users` (the existing one) is fine.

<img width="241" alt="Screenshot 2024-07-12 at 2 07 08 AM" src="https://github.com/user-attachments/assets/8341869b-787a-4c10-bbeb-7c52af8ccc66">


FYI - I believe the default behaviour is that Mongoose comes up with a collection name by taking the lowercase plural of the first argument passed to `mongoose.model`, e.g. `mongoose.model<User>("User", UserSchema)` gives you `users`.

2024-07-12 06:37 UTC, carolynzhang18 commented on backend/models/user.mgmodel.ts
> +  discriminatorKey: "type",
Hey actually... what if we have the `discriminatorKey` as `"role"` (the property that's already on User)?

By specifying a different discriminator key like `"type"`, we end up with the same thing showing up twice on facilitators and learners:
<img width="463" alt="Screenshot 2024-07-12 at 2 10 54 AM" src="https://github.com/user-attachments/assets/4dc098a9-67dc-45d6-a8bd-95391f151ee8">

The catch is that you'll have to add an `Administrator` discriminator as well (or else creating an admin will cause an error) - should be ezpz, same as what you did for facilitator/learner discriminator, just with no additional properties (for now anyway) :D

2024-07-16 23:50 UTC, cherryyng commented on backend/server.ts
> +}
Yes this will be removed after!

2024-07-17 02:11 UTC, carolynzhang18 approved these changes
![image](https://github.com/user-attachments/assets/60455918-f17f-4c50-a5bc-38ea807ec24c)

2024-07-17 02:24 UTC, merged